=== jdahlbom/ApMech/data/objectProtos.dtd
<!ELEMENT objectProtos (object+)>

<!ELEMENT object (id,name,mesh,materials)>
<!ATTLIST object type (mech|projectile) #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mesh (#PCDATA)>
<!ELEMENT materials (script*,texture*)>
<!ELEMENT script (#PCDATA)>
<!ELEMENT texture (#PCDATA)>

=== jdahlbom/ApMech/data/objectProtos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE objectProtos SYSTEM "objectProtos.dtd">

<objectProtos>
  <object type="mech">
    <id>1</id>
    <name>Crude Mech</name>
    <mesh>CrudeMesh.mesh</mesh>
    <materials>
      <script>CrudeMesh.material</script>
    </materials>
  </object>
  <object type="projectile">
    <id>1</id>
    <name>Crude Missile</name>
    <mesh>CrudeMissile.mesh</mesh>
    <materials>
      <script>CrudeMissile.material</script>
    </materials>
  </object>
</objectProtos>
